#pragma once

#define WM_MY_TRAY_NOTIFICATION						(WM_USER + 1000)
#define WM_HOTKEY_FOR_ADDFROMQRCODE					(WM_USER + 1001)
#define WM_USERLOGIN_MSG							(WM_USER + 1002) // 用户登录

#define ID_MENU_START								(WM_USER + 1999)// 菜单ID开始
#define ID_TOOLBAR_DUMMY							(WM_USER + 2000)	// 假ID不响应.
#define ID_MENU_NODES_START							(WM_USER + 2001)
#define ID_MENU_NODES_END							(WM_USER + 2999)    // 999个代理节点肯定够了吧

#define ID_MENU_ENABLE_SYSPROXY						(WM_USER + 3000) //Enable system proxy
#define ID_MENU_SYSTEM_CONFIGURE					(WM_USER + 3001) // System congifure
#define ID_MENU_HELP_OFFICIAL_PAGE					(WM_USER + 3002) // OFFICIAL PAGE
//#define ID_MENU_HELP_CONTACTME						(WM_USER + 3003) // contact me
#define ID_MENU_HELP_FEEDBACK						(WM_USER + 3004) // FEEDBACK
#define ID_MENU_EXIT								(WM_USER + 3005)

#define ID_MENU_ACTIVATE_SEELECT					(WM_USER + 3006)
#define ID_MENU_EDIT_SEELECT						(WM_USER + 3007)
#define ID_MENU_DELETE_SEELECT						(WM_USER + 3008)

#define ID_MENU_ADD_NEW								(WM_USER + 3009)
#define ID_MENU_ADD_NEW_FROM_QRCODE					(WM_USER + 3010)
#define ID_MENU_ADD_NEW_FROM_LINK					(WM_USER + 3011)
#define ID_MENU_BATCH_ADDING						(WM_USER + 3012)

#define ID_MENU_CHECK_SEELECT_TCP					(WM_USER + 3013)
#define ID_MENU_DISABLE_SEELECT						(WM_USER + 3014)
#define ID_MENU_ENABLE_SEELECT						(WM_USER + 3015)
#define ID_MENU_UPDATE_SS_FROM_WEBSITE				(WM_USER + 3016) // update ss info from website
#define ID_MENU_CHECK_SEELECT_UDP					(WM_USER + 3017)
#define ID_MENU_CHECK_PING							(WM_USER + 3018)

#define WM_MSG_FOUND_NEWVERSION						(WM_USER + 4000)
#define ID_MENU_COPY_TO_QRCODE							(WM_USER + 4001)
#define ID_MENU_COPY_TO_JSON							(WM_USER + 4002)
#define ID_MENU_COPY_TO_SSLINK							(WM_USER + 4003)

#define ID_MENU_SYSPROXY_GLOBAL_MODE				(WM_USER + 4004)
#define ID_MENU_SYSPROXY_PAC_MODE					(WM_USER + 4005)	
#define ID_MENU_SYSPROXY_EDIT_PACFILE				(WM_USER + 4006)
#define ID_MENU_SYSPROXY_UPDATE_PACFILE				(WM_USER + 4007)

#define ID_MENU_SHOW_QRCODE				(WM_USER + 4008)

#define ID_MENU_DISCONNECTALLCONNECTION				(WM_USER + 4009)
#define ID_MENU_CHECK_ALL_NODES_TCP					(WM_USER + 4010)
#define ID_MENU_CLEAR_ALL_TRAFFIC_DATA				(WM_USER + 4011)
#define ID_MENU_COPY_TO_PLAIN_NODE_INFO				(WM_USER + 4012)

#define ID_MENU_DELETE_ALLNODES						(WM_USER + 4013)

#define ID_MENU_END									(WM_USER + 4014) // 菜单ID结束

